most_frequent_terms=1
images_dir='images/'
#search_images_per_keyword=True
#total_images_per_keyword=0
search_images_per_keyword=False
total_images=1
total_colors_per_image=3
total_palettes_per_color=2